# Define GitHub Actions workflow to sync changes from public to private repository

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'  # Watch for changes in the docs folder

# Define the jobs to be executed
jobs:
  # Define a job named "test" that runs on Ubuntu latest version
  test:
    runs-on: ubuntu-latest

    # Define the steps to be executed within the job
    steps:
      # Step 1: Checkout the repository with a depth of 2
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 2  # Limit the depth of history to speed up the checkout process

      # Step 2: Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      - name: Get changed files
        run: git diff HEAD^ HEAD docs/

      # Step 3: Sync changes from public to private repository using Gulp
      - name: Sync
        run: npm run publish  # Run the Gulp task to synchronize changes
        
        # Set environment variables required by the Gulp task
        env:
          GIT_USER: ${{ secrets.GIT_USERNAME }}  # GitHub username
          GIT_TOKEN: ${{ secrets.PRIVATE_REPO }}  # GitHub personal access token for private repository
          GIT_MAIL: ${{ secrets.GIT_EMAIL }}  # Email associated with GitHub account
