# Define GitHub Actions workflow to run tests on pull requests

# Trigger the workflow on pull request events targeting the main branch
on:
  pull_request:
    branches:
      - master

# Define the jobs to be executed
jobs:
  # Define a job named "test" that runs on Ubuntu latest version
  test:
    runs-on: ubuntu-latest

    # Define the steps to be executed within the job
    steps:
      # Step 1: Checkout the repository with a depth of 2
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Limit the depth of history to speed up the checkout process

      # Step 2: Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Step 3: Run tests
      - name: Test
        run: npm run test  # Execute the npm test script to run tests
